name = "DualOptimalFiltering"
uuid = "7baf8b3f-9d52-46d6-903d-a738528ccf5a"
authors = ["konkam <guillaume.konkamking.work@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExactWrightFisher = "8c1589a6-e1d0-11e8-3509-29fca4fccf6a"
FeynmanKacParticleFilters = "b43f8e06-e683-11e8-294f-8d3ef32cb08c"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
KernelEstimator = "857edff2-01a9-55ba-8bc9-13e46c0ddbb2"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
