name = "DualOptimalFiltering"
uuid = "7baf8b3f-9d52-46d6-903d-a738528ccf5a"
authors = ["konkam <guillaume.konkamking.work@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
